@startuml
!include style.puml

box "Logic" LOGIC_COLOR_T1
participant "rc:RemarkCommand" as RemarkCommand LOGIC_COLOR
end box

box "Storage" STORAGE_COLOR_T1
participant ":StorageManager" as StorageManager STORAGE_COLOR
participant ":JsonAddressBookStorage" as JsonAddressBookStorage STORAGE_COLOR
participant ":JsonSerializableAddressBook" as JsonSerializableAddressBook STORAGE_COLOR
participant ":JsonAdaptedPerson" as JsonAdaptedPerson STORAGE_COLOR
participant ":JsonAdaptedRemark" as JsonAdaptedRemark STORAGE_COLOR
end box

activate RemarkCommand

RemarkCommand -> StorageManager : saveAddressBook(addressBook)
activate StorageManager

StorageManager -> JsonAddressBookStorage : saveAddressBook(addressBook)
activate JsonAddressBookStorage

JsonAddressBookStorage -> JsonSerializableAddressBook : new JsonSerializableAddressBook(addressBook)
activate JsonSerializableAddressBook

loop for each Person
    JsonSerializableAddressBook -> JsonAdaptedPerson : new JsonAdaptedPerson(person)
    activate JsonAdaptedPerson

    loop for each Remark
        JsonAdaptedPerson -> JsonAdaptedRemark : new JsonAdaptedRemark(remark)
        activate JsonAdaptedRemark
        JsonAdaptedRemark --> JsonAdaptedPerson
        deactivate JsonAdaptedRemark
    end

    JsonAdaptedPerson --> JsonSerializableAddressBook
    deactivate JsonAdaptedPerson
end

JsonSerializableAddressBook --> JsonAddressBookStorage
deactivate JsonSerializableAddressBook

JsonAddressBookStorage --> StorageManager
deactivate JsonAddressBookStorage

StorageManager --> RemarkCommand : save complete
deactivate StorageManager

deactivate RemarkCommand

@enduml
